### ISSUE TITLE
Error with "ffmpeg"

### ISSUE THREAD

**Issue by serejajar** [xaviviro/refacer#12]
OS: Ubuntu 22.04.2 LTS
Video: [link](https://github.com/xaviviro/refacer/assets/8776260/386168ae-1dd4-40a0-acdd-1cb7b98341d7)
Command: python3 app.py 
Video codec for FFMPEG: h264_nvenc
CPU mode with providers ['CPUExecutionProvider']

Output:
```
Total frames: 159
Extracting frames: 100%|████████████████████| 159/159 [00:00<00:00, 1319.79it/s]
Processing frames: 100%|██████████████████████| 159/159 [02:02<00:00,  1.29it/s]
Merging audio with the refaced video...
Traceback (most recent call last):
  File "/home/serejajar/.local/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/serejajar/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/serejajar/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/serejajar/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/serejajar/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/serejajar/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/serejajar/Documents/my/refacer/app.py", line 30, in run
    return refacer.reface(video_path,faces)
  File "/home/serejajar/Documents/my/refacer/refacer.py", line 189, in reface
    return self.__convert_video(video_path,output_video_path)
  File "/home/serejajar/Documents/my/refacer/refacer.py", line 113, in __convert_video
    out.run(overwrite_output=True,quiet=True)
  File "/home/serejajar/.local/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by serejajar** [comment]
Thanks for your fast answer! I changed 'quiet' to 'False':

```
Video codec for FFMPEG: h264_nvenc
CPU mode with providers ['CPUExecutionProvider']
inswapper-shape: [1, 3, 128, 128]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total frames: 159
Extracting frames: 100%|████████████████████| 159/159 [00:00<00:00, 1983.78it/s]
Processing frames: 100%|██████████████████████| 159/159 [02:02<00:00,  1.29it/s]
Merging audio with the refaced video...
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'out/16856869624730.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:05.30, start: 0.000000, bitrate: 653 kb/s
  Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 480x480 [SAR 1:1 DAR 1:1], 651 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/gradio/e3d21665794847904dedecff47025814207278c5/16856869624730.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2022-12-28T16:13:57.000000Z
  Duration: 00:00:05.36, start: 0.000000, bitrate: 900 kb/s
  Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default)
    Metadata:
      creation_time   : 2022-12-28T16:13:52.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
  Stream #1:1(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 480x480, 837 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2022-12-28T16:13:52.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (h264_nvenc))
  Stream #1:0 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_nvenc @ 0x56147cab9300] Cannot load libcuda.so.1
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
Traceback (most recent call last):
  File "/home/serejajar/.local/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/serejajar/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/serejajar/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/serejajar/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/serejajar/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/serejajar/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/serejajar/Documents/my/refacer/app.py", line 30, in run
    return refacer.reface(video_path,faces)
  File "/home/serejajar/Documents/my/refacer/refacer.py", line 189, in reface
    return self.__convert_video(video_path,output_video_path)
  File "/home/serejajar/Documents/my/refacer/refacer.py", line 113, in __convert_video
    out.run(overwrite_output=True,quiet=False)
  File "/home/serejajar/.local/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by xaviviro** [comment]
Thank you! For some reason, ffmpeg shows that you have the Nvidia nvec encoder, but then it can't find it. I'll fix this. In the meantime, if you want to continue using Refacer until I solve this, you can comment out this line https://github.com/xaviviro/refacer/blob/ef9b64ad92b5f363b12288c9122e49fe74118773/refacer.py#L209 like this:

```python
#'h264_nvenc', #NVIDIA HW acceleration
```

**Comment by serejajar** [comment]
Thank you!

**Comment by serejajar** [comment]
Do I need to close the issue or U want to do it after the fix?

**Comment by xaviviro** [comment]
Don't worry, I'll close it when I solve it, that way I'll remember xD.
