### ISSUE TITLE
Error occured while launching app.py

### ISSUE THREAD

**Issue by rmhckrkz** [xaviviro/refacer#24]
C:\Python\REFACE\refacer>python app.py
Trying FFMPEG h264_nvenc encoder
FFMPEG h264_nvenc encoder works
Video codec for FFMPEG: h264_nvenc
CPU mode with providers ['CPUExecutionProvider']
Traceback (most recent call last):
  File "C:\Python\REFACE\refacer\app.py", line 12, in <module>
    refacer = Refacer(force_cpu=args.force_cpu,colab_performance=args.colab_performance)
  File "C:\Python\REFACE\refacer\refacer.py", line 35, in __init__
    self.__init_apps()
  File "C:\Python\REFACE\refacer\refacer.py", line 95, in __init_apps
    self.face_swapper = INSwapper(model_path,sess_swap)
  File "C:\Users\RMuratuly\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\insightface\model_zoo\inswapper.py", line 16, in __init__
    model = onnx.load(self.model_file)
  File "C:\Users\RMuratuly\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnx\__init__.py", line 170, in load_model
    model = load_model_from_string(s, format=format)
  File "C:\Users\RMuratuly\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnx\__init__.py", line 212, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "C:\Users\RMuratuly\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnx\__init__.py", line 143, in _deserialize
    decoded = typing.cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message

**Comment by xaviviro** [comment]
In English, your response would be:

It appears that your error may be related to the version of ONNX Runtime you have installed. You need version 1.15.0. You can install it by running: `pip install --ignore-installed onnxruntime-gpu==1.15.0`

**Comment by xaviviro** [comment]
It appears that your error may be related to the version of ONNX Runtime you have installed. You need version 1.15.0. You can install it by running: `pip install --ignore-installed onnxruntime-gpu==1.15.0`
