### ISSUE TITLE
FileNotFoundError when start

### ISSUE THREAD

**Issue by denchebur** [xaviviro/refacer#25]
installed with tutorial, but when run app.py it seems like this:
Traceback (most recent call last):
  File "D:\work\a\verify\refacer\app.py", line 17, in <module>
    refacer = Refacer(force_cpu=args.force_cpu,colab_performance=args.colab_performance)
  File "D:\work\a\verify\refacer\refacer.py", line 32, in __init__
    self.__check_encoders()
  File "D:\work\a\verify\refacer\refacer.py", line 230, in __check_encoders
    commandout = subprocess.run(command, check=True, capture_output=True).stdout
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by xaviviro** [comment]
Could you please paste the result of running ffmpeg in the same terminal where you've executed Refacer?

**Comment by xaviviro** [comment]
duplicated: #12
