### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by Famper** [xaviviro/refacer#29]
```(.venv) *@*-H*M-H-V3:~/Desktop/refacer$ python3 app.py
Traceback (most recent call last):
  File "/home/*/Desktop/refacer/app.py", line 17, in <module>
    refacer = Refacer(force_cpu=args.force_cpu,colab_performance=args.colab_performance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/*/Desktop/refacer/refacer.py", line 32, in __init__
    self.__check_encoders()
  File "/home/*/Desktop/refacer/refacer.py", line 230, in __check_encoders
    commandout = subprocess.run(command, check=True, capture_output=True).stdout
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Comment by xaviviro** [comment]
duplicated: #12
