### ISSUE TITLE
ConnectionResetError 

### ISSUE THREAD

**Issue by azoksky** [xaviviro/refacer#4]
This error pops up after muxing the frames and job completion. This doesn't seem to be affecting anything as app still works and does swapping repeatedly. 

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run

**Comment by xaviviro** [comment]
Can you confirm if you've tried with the latest commits? Specifically, I've introduced queue which might address this issue.

**Comment by azoksky** [comment]
Yes, I did a git pull and reinstalled all dependencies. Actually am not sure if it has anything to do with my python installation. Iam on 3.10.6 and all dependencies are in a venv. Nevertheless, I am so happy using this amazing tool... In terms of processing speed, roop has an upper hand with their latest gpu thread optimisations. But roop can't catch up with your implementation till they do face-specific swapping.

**Comment by xaviviro** [comment]
Thanks for your comment. I've looked into roop and noticed that one of the things speeding it up is multi-thread frame processing. I could definitely consider implementing that as well. Your feedback is appreciated.
