### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by txiflo** [xaviviro/refacer#48]
Everything fine, but when I try to make it work this error appears:
Something went wrong
ffmpeg error (see stderr output for detail)

What should I do to get throught this?

**Comment by a11e** [comment]
same here..
Processing frames: 100%|████████████████████████████████████████| 273/273 [03:09<00:00,  1.44it/s]
Merging audio with the refaced video...
Traceback (most recent call last):
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/mac/develop/refacer/app.py", line 64, in run
    return refacer.reface(video_path,faces)
  File "/Users/mac/develop/refacer/refacer.py", line 222, in reface
    return self.__convert_video(video_path,output_video_path)
  File "/Users/mac/develop/refacer/refacer.py", line 126, in __convert_video
    out.run(overwrite_output=True,quiet=True)
  File "/Users/mac/anaconda3/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by Cipherbunker** [comment]
running this fixed my ffmpeg error https://github.com/s0md3v/roop/wiki/1.-Installation
