### ISSUE TITLE
The localhost doesn't work normally.

### ISSUE THREAD

**Issue by SkywalkerLuke** [xaviviro/refacer#66]
It seems that the localhost is not working, when I set the refacer on the Linux.
![image](https://github.com/xaviviro/refacer/assets/86698972/0f1686fb-db26-4703-bf45-d92732ad755e)

**Comment by SkywalkerLuke** [comment]
![image](https://github.com/xaviviro/refacer/assets/86698972/a1e25a9f-2477-4254-a54c-70debf13fce9)
And the shell is like this.

**Comment by xynta** [comment]
Have similar problem on macos.
When press "Reface" queue start count, but nothing happened.
There are no logs in console, no cpu load.
<img width="470" alt="cpu activity" src="https://github.com/xaviviro/refacer/assets/2022222/5fe134b4-2a4d-4a23-946f-fe1462f96a4b">
Waiting few hours leads to error in webui
<img width="768" alt="Screenshot at Jul 30 17-22-20" src="https://github.com/xaviviro/refacer/assets/2022222/293b0d16-d133-4f8f-ac97-b3e69ec17012">
If press Reface again after error messages in log:
```
(venv) (base) admin@admins-MBP-2 refacer % python app.py                    
Trying FFMPEG h264_videotoolbox encoder
FFMPEG h264_videotoolbox encoder works
Video codec for FFMPEG: h264_videotoolbox
CPU mode with providers ['CPUExecutionProvider']
inswapper-shape: [1, 3, 128, 128]
Running on local URL:  http://127.0.0.1:7860/

Task exception was never retrieved
future: <Task finished name='j4xebw3ra3d_0' coro=<Queue.process_events() done, defined at /Users/admin/PycharmProjects/refacer/venv/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[{'data': 'data...on_hash': 'j4xebw3ra3d'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/refacer/venv/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/Users/admin/PycharmProjects/refacer/venv/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/Users/admin/PycharmProjects/refacer/venv/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/Users/admin/PycharmProjects/refacer/venv/lib/python3.10/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[{'data': 'data...on_hash': 'j4xebw3ra3d'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
```

Also tied with COREML, CPU, --max_num_faces 1, --force_cpu, --share_gradio and API example.
roop via sd and standalone work on this machine.

Any advice how to find a problem?
---
Tech specs:
MacOS Ventura 13.4
MBP M1 32gb ram

**Comment by mwiater** [comment]
Updating the gradio version in the requirements.txt file and re-running `pip install -r requirements.txt` fixed this issue for me. 

`gradio==3.36.1`

FYI, I'm running in CPU mode on Ubuntu 22 with only the `--server-name` flag: `python3 app.py --server_name 192.168.0.98`

**Comment by xynta** [comment]
[mwiater](https://github.com/mwiater) thank you! It work for me too!

**Comment by SkywalkerLuke** [comment]
It also works for me. However, I wonder whether the authors can update a python root for us to use, not only the localhost.
