### ISSUE TITLE
Error and doesn't work 

### ISSUE THREAD

**Issue by ShvetsAaa** [xaviviro/refacer#67]
Traceback (most recent call last):
  File "/content/refacer/app.py", line 70, in <module>
    with gr.Blocks() as demo:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1478, in __exit__
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 220, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 706, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 645, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 491, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 268, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 111, in get_param_sub_dependant
    return get_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 289, in get_dependant
    add_param_to_fields(field=param_field, dependant=dependant)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 462, in add_param_to_fields
    if field_info.in_ == params.ParamTypes.path:
AttributeError: 'FieldInfo' object has no attribute 'in_'

**Comment by badunch** [comment]
getting the same

**Comment by ShvetsAaa** [comment]
Working again:)
