### ISSUE TITLE
Hello, dnt work on colab 

### ISSUE THREAD

**Issue by 6ThomasDittrich9** [xaviviro/refacer#77]
Traceback (most recent call last):
  File "/content/refacer/app.py", line 17, in <module>
    refacer = Refacer(force_cpu=args.force_cpu,colab_performance=args.colab_performance)
  File "/content/refacer/refacer.py", line 35, in __init__
    self.__init_apps()
  File "/content/refacer/refacer.py", line 94, in __init_apps
    sess_swap = rt.InferenceSession(model_path, self.sess_options, providers=self.providers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from inswapper_128.onnx failed:Load model inswapper_128.onnx failed. File doesn't exist

**Comment by 6ThomasDittrich9** [comment]
UPD. 
![image](https://github.com/xaviviro/refacer/assets/142996963/143b65f0-0286-4243-b209-73c3b291fe5c)

**Comment by 6ThomasDittrich9** [comment]
![image](https://github.com/xaviviro/refacer/assets/142996963/debf7ccc-1abe-4b10-b6ff-28fb0e9cecd7)

**Comment by JRC100** [comment]
I know a colab that is using this Civitai link to the .onnx file and it's currently working
`!wget https://civitai.com/api/download/models/85159 -O inswapper_128.onnx`
Hope it helps
